# permissions for end users to edit wens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wen-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: crd-controller
    app.kubernetes.io/part-of: crd-controller
    app.kubernetes.io/managed-by: kustomize
  name: wen-editor-role
rules:
- apiGroups:
  - kubebin.com.my.domain
  resources:
  - wens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebin.com.my.domain
  resources:
  - wens/status
  verbs:
  - get
